// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lutupbdrklinothptcwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dHVwYmRya2xpbm90aHB0Y3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTEwMjYsImV4cCI6MjA1NzIyNzAyNn0.ykIEN6G2sBaJGyuCT0S8lS5BsIfLmsqseXlaq1CzQOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);